//! ES10b card functions for download, authentication, and notifications.

use sha2::{Digest, Sha256};

use crate::apdu::{CardRequest, CardResponse};
use crate::bertlv::primitive::{decode_bool, decode_i64, encode_bit_string};
use crate::bertlv::{Class, DecodeTlv, EncodeTlv, Form, Tag, Tlv};
use crate::bpp::validate_bound_profile_package;
use crate::error::{
    AuthenticateErrorCode, AuthenticateResponseError, BppCommandId, BppErrorReason, EuiccError,
    LoadBoundProfilePackageError, Result,
};
use crate::identifier::{HexBytes, Imei, IsdpAid};
use crate::notification::{
    NotificationEvent, NotificationMetadata, PendingNotification, SequenceNumber,
};

/// ES10b.PrepareDownload request.
///
/// # Errors
///
/// Encoding returns [`EuiccError::MissingField`] when a confirmation code is
/// required by `smdpSigned2` but not provided.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PrepareDownloadRequest {
    /// Transaction id generated by the RSP server.
    pub transaction_id: HexBytes,
    /// Profile metadata from ES9+.AuthenticateClient when present.
    pub profile_metadata: Option<Tlv>,
    /// SM-DP+ signed2 TLV.
    pub signed2: Tlv,
    /// SM-DP+ signature2 TLV.
    pub signature2: Tlv,
    /// SM-DP+ certificate TLV.
    pub certificate: Tlv,
    /// Optional confirmation code entered by the user.
    pub confirmation_code: Option<Vec<u8>>,
}

impl PrepareDownloadRequest {
    /// Returns true when `smdpSigned2` requires a confirmation code.
    #[must_use]
    pub fn need_confirmation_code(&self) -> bool {
        self.signed2
            .first(&Class::Universal.primitive(1))
            .and_then(Tlv::value)
            .is_some_and(decode_bool)
    }

    /// Computes the SGP.22 hashCc value.
    #[must_use]
    pub fn hashed_confirmation_code(&self) -> Option<Vec<u8>> {
        if !self.need_confirmation_code() {
            return None;
        }
        let code = self.confirmation_code.as_ref()?;
        let first = Sha256::digest(code);
        let mut hasher = Sha256::new();
        hasher.update(first);
        hasher.update(self.transaction_id.as_bytes());
        Some(hasher.finalize().to_vec())
    }
}

impl EncodeTlv for PrepareDownloadRequest {
    fn to_tlv(&self) -> Result<Tlv> {
        if self.need_confirmation_code() && self.confirmation_code.is_none() {
            return Err(EuiccError::MissingField("confirmationCode"));
        }
        let mut children = Vec::with_capacity(4);
        children.push(self.signed2.clone());
        children.push(self.signature2.clone());
        if let Some(hash) = self.hashed_confirmation_code() {
            children.push(Tlv::primitive(Class::Universal.primitive(4), hash)?);
        }
        children.push(self.certificate.clone());
        constructed(33, children)
    }
}

impl CardRequest for PrepareDownloadRequest {
    type Response = PrepareDownloadResponse;

    fn decode_response(&self, tlv: &Tlv) -> Result<Self::Response> {
        PrepareDownloadResponse::from_tlv(tlv)
    }
}

/// ES10b.PrepareDownload response.
///
/// # Errors
///
/// Decoding returns [`EuiccError::UnexpectedTag`] when the tag is not `[33]`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PrepareDownloadResponse {
    /// Raw PrepareDownloadResponse TLV.
    pub response: Tlv,
}

impl DecodeTlv for PrepareDownloadResponse {
    fn from_tlv(tlv: &Tlv) -> Result<Self> {
        ensure_tag(tlv, 33, "prepareDownloadResponse")?;
        Ok(Self {
            response: tlv.clone(),
        })
    }
}

impl PrepareDownloadResponse {
    /// Decodes the response from a TLV.
    ///
    /// # Errors
    ///
    /// Returns [`EuiccError::UnexpectedTag`] when the tag is not `[33]`.
    pub fn from_tlv(tlv: &Tlv) -> Result<Self> {
        <Self as DecodeTlv>::from_tlv(tlv)
    }
}

impl CardResponse for PrepareDownloadResponse {}

/// ES10b.LoadBoundProfilePackage request wrapper.
///
/// # Errors
///
/// Encoding returns validation errors when the wrapped TLV is not a BPP.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LoadBoundProfilePackageRequest {
    /// BoundProfilePackage TLV.
    pub bound_profile_package: Tlv,
}

impl EncodeTlv for LoadBoundProfilePackageRequest {
    fn to_tlv(&self) -> Result<Tlv> {
        validate_bound_profile_package(&self.bound_profile_package)?;
        Ok(self.bound_profile_package.clone())
    }
}

impl CardRequest for LoadBoundProfilePackageRequest {
    type Response = LoadBoundProfilePackageResponse;

    fn decode_response(&self, tlv: &Tlv) -> Result<Self::Response> {
        LoadBoundProfilePackageResponse::from_tlv(tlv)
    }
}

/// ES10b.LoadBoundProfilePackage response.
///
/// # Errors
///
/// Decoding returns [`EuiccError`] when mandatory fields are absent.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LoadBoundProfilePackageResponse {
    /// Transaction id returned in ProfileInstallationResult.
    pub transaction_id: HexBytes,
    /// Notification metadata returned by the card.
    pub notification: NotificationMetadata,
    /// Final result TLV.
    pub final_result: Tlv,
}

impl DecodeTlv for LoadBoundProfilePackageResponse {
    fn from_tlv(tlv: &Tlv) -> Result<Self> {
        ensure_tag(tlv, 55, "profileInstallationResult")?;
        let result = tlv
            .first(&Class::ContextSpecific.constructed(39))
            .ok_or(EuiccError::MissingField("profileInstallationResultData"))?;
        let transaction_id = HexBytes::from_bytes(required_value(
            result,
            Class::ContextSpecific.primitive(0),
            "transactionId",
        )?);
        let final_result = result
            .first(&Class::ContextSpecific.constructed(2))
            .ok_or(EuiccError::MissingField("finalResult"))?
            .clone();
        let notification = NotificationMetadata::from_tlv(
            result
                .first(&Class::ContextSpecific.constructed(47))
                .ok_or(EuiccError::MissingField("notificationMetadata"))?,
        )?;
        Ok(Self {
            transaction_id,
            notification,
            final_result,
        })
    }
}

impl LoadBoundProfilePackageResponse {
    /// Decodes the response from a TLV.
    ///
    /// # Errors
    ///
    /// Returns [`EuiccError`] when mandatory fields are absent or malformed.
    pub fn from_tlv(tlv: &Tlv) -> Result<Self> {
        <Self as DecodeTlv>::from_tlv(tlv)
    }

    /// Returns the installed ISD-P AID when the final result is successful.
    #[must_use]
    pub fn isdp_aid(&self) -> Option<IsdpAid> {
        let success = self
            .final_result
            .first(&Class::ContextSpecific.constructed(0))?;
        let aid = success.first(&Class::Application.primitive(15))?.value()?;
        Some(IsdpAid::from_bytes(aid.to_vec()))
    }
}

impl CardResponse for LoadBoundProfilePackageResponse {
    fn validate(&self) -> Result<()> {
        let Some(result) = self
            .final_result
            .first(&Class::ContextSpecific.constructed(1))
        else {
            return Ok(());
        };
        let command_id = BppCommandId::from_i64(required_int(
            result,
            Class::ContextSpecific.primitive(0),
            "bppCommandId",
            1,
        )?);
        let reason = BppErrorReason::from_i64(required_int(
            result,
            Class::ContextSpecific.primitive(1),
            "bppErrorReason",
            1,
        )?);
        Err(LoadBoundProfilePackageError::new(command_id, reason).into())
    }
}

/// ES10b.GetEuiccChallenge request.
#[derive(Debug, Copy, Clone, PartialEq, Eq, Default)]
pub struct GetEuiccChallengeRequest;

impl EncodeTlv for GetEuiccChallengeRequest {
    fn to_tlv(&self) -> Result<Tlv> {
        constructed(46, Vec::new())
    }
}

impl CardRequest for GetEuiccChallengeRequest {
    type Response = GetEuiccChallengeResponse;

    fn decode_response(&self, tlv: &Tlv) -> Result<Self::Response> {
        GetEuiccChallengeResponse::from_tlv(tlv)
    }
}

/// ES10b.GetEuiccChallenge response.
///
/// # Errors
///
/// Decoding returns [`EuiccError`] when the tag or challenge field is missing.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GetEuiccChallengeResponse {
    /// eUICC challenge bytes.
    pub challenge: Vec<u8>,
}

impl DecodeTlv for GetEuiccChallengeResponse {
    fn from_tlv(tlv: &Tlv) -> Result<Self> {
        ensure_tag(tlv, 46, "getEuiccChallengeResponse")?;
        let child = required_fixed_value(tlv, octet_string_tag(), "euiccChallenge", 16)?;
        Ok(Self {
            challenge: child.to_vec(),
        })
    }
}

impl GetEuiccChallengeResponse {
    /// Decodes the response from a TLV.
    ///
    /// # Errors
    ///
    /// Returns [`EuiccError`] when the response is malformed.
    pub fn from_tlv(tlv: &Tlv) -> Result<Self> {
        <Self as DecodeTlv>::from_tlv(tlv)
    }
}

impl CardResponse for GetEuiccChallengeResponse {}

/// EUICCInfo response version.
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum EuiccInfoVersion {
    /// EUICCInfo1, tag `[32]`.
    V1,
    /// EUICCInfo2, tag `[34]`.
    V2,
}

impl EuiccInfoVersion {
    /// Returns the request and response tag number.
    #[must_use]
    pub const fn tag_value(self) -> u64 {
        match self {
            Self::V1 => 32,
            Self::V2 => 34,
        }
    }
}

/// ES10b.GetEUICCInfo request.
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct GetEuiccInfoRequest {
    /// Requested info version.
    pub version: EuiccInfoVersion,
}

impl EncodeTlv for GetEuiccInfoRequest {
    fn to_tlv(&self) -> Result<Tlv> {
        constructed(self.version.tag_value(), Vec::new())
    }
}

impl CardRequest for GetEuiccInfoRequest {
    type Response = GetEuiccInfoResponse;

    fn decode_response(&self, tlv: &Tlv) -> Result<Self::Response> {
        GetEuiccInfoResponse::from_tlv(tlv)
    }
}

/// ES10b.GetEUICCInfo response wrapper.
///
/// # Errors
///
/// Decoding returns [`EuiccError::UnexpectedTag`] when the response is not
/// `[32]` or `[34]`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GetEuiccInfoResponse {
    /// Decoded response version.
    pub version: EuiccInfoVersion,
    /// Raw EUICCInfo TLV.
    pub response: Tlv,
}

impl DecodeTlv for GetEuiccInfoResponse {
    fn from_tlv(tlv: &Tlv) -> Result<Self> {
        let version = match tlv.tag().value() {
            32 if tlv.tag().is(Class::ContextSpecific, Form::Constructed, 32) => {
                EuiccInfoVersion::V1
            }
            34 if tlv.tag().is(Class::ContextSpecific, Form::Constructed, 34) => {
                EuiccInfoVersion::V2
            }
            _ => {
                return Err(EuiccError::UnexpectedTag {
                    expected: "euiccInfo",
                    actual: tlv.tag().hex(),
                });
            }
        };
        Ok(Self {
            version,
            response: tlv.clone(),
        })
    }
}

impl GetEuiccInfoResponse {
    /// Decodes the response from a TLV.
    ///
    /// # Errors
    ///
    /// Returns [`EuiccError::UnexpectedTag`] when the response tag is invalid.
    pub fn from_tlv(tlv: &Tlv) -> Result<Self> {
        <Self as DecodeTlv>::from_tlv(tlv)
    }
}

impl CardResponse for GetEuiccInfoResponse {}

/// ES10b.ListNotification request.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct ListNotificationRequest {
    /// Optional notification event filter.
    pub filter: Option<Vec<NotificationEvent>>,
}

impl EncodeTlv for ListNotificationRequest {
    fn to_tlv(&self) -> Result<Tlv> {
        let mut children = Vec::new();
        if let Some(events) = &self.filter {
            children.push(Tlv::primitive(
                Class::ContextSpecific.primitive(1),
                event_filter_bytes(events),
            )?);
        }
        constructed(40, children)
    }
}

impl CardRequest for ListNotificationRequest {
    type Response = ListNotificationResponse;

    fn decode_response(&self, tlv: &Tlv) -> Result<Self::Response> {
        ListNotificationResponse::from_tlv(tlv)
    }
}

/// ES10b.ListNotification response.
///
/// # Errors
///
/// Decoding returns [`EuiccError`] for malformed notification entries or error
/// result codes.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct ListNotificationResponse {
    /// Notification metadata entries.
    pub notifications: Vec<NotificationMetadata>,
}

impl DecodeTlv for ListNotificationResponse {
    fn from_tlv(tlv: &Tlv) -> Result<Self> {
        ensure_tag(tlv, 40, "listNotificationResponse")?;
        if let Some(error) = tlv.first(&Class::ContextSpecific.primitive(1)) {
            return match decode_i64(error.value().unwrap_or_default(), 1)? {
                127 => Err(EuiccError::Undefined),
                _ => Err(EuiccError::Undefined),
            };
        }
        let Some(choice) = tlv.first(&Class::ContextSpecific.constructed(0)) else {
            let Some(child) = tlv.children().unwrap_or_default().first() else {
                return Ok(Self::default());
            };
            return Err(EuiccError::UnexpectedTag {
                expected: "notificationMetadataList",
                actual: child.tag().hex(),
            });
        };

        let mut notifications = Vec::new();
        for child in choice.children().unwrap_or_default() {
            if child
                .tag()
                .is(Class::ContextSpecific, Form::Constructed, 47)
            {
                notifications.push(NotificationMetadata::from_tlv(child)?);
            }
        }
        Ok(Self { notifications })
    }
}

impl ListNotificationResponse {
    /// Decodes the response from a TLV.
    ///
    /// # Errors
    ///
    /// Returns [`EuiccError`] when entries are malformed or the response carries
    /// an error result.
    pub fn from_tlv(tlv: &Tlv) -> Result<Self> {
        <Self as DecodeTlv>::from_tlv(tlv)
    }
}

impl CardResponse for ListNotificationResponse {}

/// Search criterion for ES10b.RetrieveNotificationsList.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum NotificationSearchCriterion {
    /// Search by sequence number.
    SequenceNumber(SequenceNumber),
    /// Search by notification event.
    Event(NotificationEvent),
}

impl NotificationSearchCriterion {
    fn to_tlv(&self) -> Result<Tlv> {
        match self {
            Self::SequenceNumber(sequence) => {
                Tlv::primitive(Class::ContextSpecific.primitive(0), sequence.to_bytes())
            }
            Self::Event(event) => {
                Tlv::primitive(Class::ContextSpecific.primitive(1), event.to_bytes())
            }
        }
    }
}

/// ES10b.RetrieveNotificationsList request.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct RetrieveNotificationsListRequest {
    /// Optional search criterion.
    pub search_criterion: Option<NotificationSearchCriterion>,
}

impl EncodeTlv for RetrieveNotificationsListRequest {
    fn to_tlv(&self) -> Result<Tlv> {
        let mut children = Vec::new();
        if let Some(search) = &self.search_criterion {
            children.push(Tlv::constructed(
                Class::ContextSpecific.constructed(0),
                vec![search.to_tlv()?],
            )?);
        }
        constructed(43, children)
    }
}

impl CardRequest for RetrieveNotificationsListRequest {
    type Response = RetrieveNotificationsListResponse;

    fn decode_response(&self, tlv: &Tlv) -> Result<Self::Response> {
        RetrieveNotificationsListResponse::from_tlv(tlv)
    }
}

/// ES10b.RetrieveNotificationsList response.
///
/// # Errors
///
/// Decoding returns [`EuiccError`] when entries are malformed or the response
/// carries an error result.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct RetrieveNotificationsListResponse {
    /// Pending notifications.
    pub notifications: Vec<PendingNotification>,
}

impl DecodeTlv for RetrieveNotificationsListResponse {
    fn from_tlv(tlv: &Tlv) -> Result<Self> {
        ensure_tag(tlv, 43, "retrieveNotificationsListResponse")?;
        if let Some(error) = tlv.first(&Class::ContextSpecific.primitive(1)) {
            return match decode_i64(error.value().unwrap_or_default(), 1)? {
                127 => Err(EuiccError::Undefined),
                _ => Err(EuiccError::Undefined),
            };
        }
        let Some(choice) = tlv.first(&Class::ContextSpecific.constructed(0)) else {
            let Some(child) = tlv.children().unwrap_or_default().first() else {
                return Ok(Self::default());
            };
            return Err(EuiccError::UnexpectedTag {
                expected: "notificationList",
                actual: child.tag().hex(),
            });
        };
        let mut notifications = Vec::new();
        for child in choice.children().unwrap_or_default() {
            notifications.push(PendingNotification::from_tlv(child)?);
        }
        Ok(Self { notifications })
    }
}

impl RetrieveNotificationsListResponse {
    /// Decodes the response from a TLV.
    ///
    /// # Errors
    ///
    /// Returns [`EuiccError`] when entries are malformed or the response carries
    /// an error result.
    pub fn from_tlv(tlv: &Tlv) -> Result<Self> {
        <Self as DecodeTlv>::from_tlv(tlv)
    }
}

impl CardResponse for RetrieveNotificationsListResponse {}

/// ES10b.RemoveNotificationFromList request.
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct NotificationSentRequest {
    /// Sequence number to remove from the pending list.
    pub sequence_number: SequenceNumber,
}

impl EncodeTlv for NotificationSentRequest {
    fn to_tlv(&self) -> Result<Tlv> {
        constructed(
            48,
            vec![Tlv::primitive(
                Class::ContextSpecific.primitive(0),
                self.sequence_number.to_bytes(),
            )?],
        )
    }
}

impl CardRequest for NotificationSentRequest {
    type Response = NotificationSentResponse;

    fn decode_response(&self, tlv: &Tlv) -> Result<Self::Response> {
        NotificationSentResponse::from_tlv(tlv)
    }
}

/// Remove-notification result code.
///
/// # Errors
///
/// Unknown values are represented by [`Self::Unknown`].
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum DeleteNotificationStatus {
    /// Operation completed successfully.
    Ok,
    /// No pending notification matched the sequence number.
    NothingToDelete,
    /// Undefined card error.
    UndefinedError,
    /// Unknown status.
    Unknown(i8),
}

impl DeleteNotificationStatus {
    /// Decodes a signed status code.
    #[must_use]
    pub const fn from_i64(value: i64) -> Self {
        match value {
            0 => Self::Ok,
            1 => Self::NothingToDelete,
            127 => Self::UndefinedError,
            other => Self::Unknown(other as i8),
        }
    }
}

/// ES10b.RemoveNotificationFromList response.
///
/// # Errors
///
/// Decoding returns [`EuiccError`] when the response tag or status field is
/// malformed.
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct NotificationSentResponse {
    /// Delete notification status.
    pub status: DeleteNotificationStatus,
}

impl DecodeTlv for NotificationSentResponse {
    fn from_tlv(tlv: &Tlv) -> Result<Self> {
        ensure_tag(tlv, 48, "notificationSentResponse")?;
        Ok(Self {
            status: DeleteNotificationStatus::from_i64(required_int(
                tlv,
                Class::ContextSpecific.primitive(0),
                "deleteNotificationStatus",
                1,
            )?),
        })
    }
}

impl NotificationSentResponse {
    /// Decodes the response from a TLV.
    ///
    /// # Errors
    ///
    /// Returns [`EuiccError`] when the response is malformed.
    pub fn from_tlv(tlv: &Tlv) -> Result<Self> {
        <Self as DecodeTlv>::from_tlv(tlv)
    }
}

impl CardResponse for NotificationSentResponse {
    fn validate(&self) -> Result<()> {
        match self.status {
            DeleteNotificationStatus::Ok => Ok(()),
            DeleteNotificationStatus::NothingToDelete => Err(EuiccError::NothingToDelete),
            DeleteNotificationStatus::UndefinedError | DeleteNotificationStatus::Unknown(_) => {
                Err(EuiccError::Undefined)
            }
        }
    }
}

/// ES10b.AuthenticateServer request.
///
/// # Errors
///
/// Encoding returns [`EuiccError::MissingField`] when the IMEI is too short for
/// the TAC field.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AuthenticateServerRequest {
    /// Transaction id generated by the RSP server.
    pub transaction_id: HexBytes,
    /// ServerSigned1 TLV.
    pub signed1: Tlv,
    /// Server signature TLV.
    pub signature1: Tlv,
    /// CI public key identifier TLV to be used.
    pub used_issuer: Tlv,
    /// Server certificate TLV.
    pub certificate: Tlv,
    /// Device IMEI in swapped BCD.
    pub imei: Imei,
    /// Optional MatchingId text.
    pub matching_id: Option<String>,
}

impl EncodeTlv for AuthenticateServerRequest {
    fn to_tlv(&self) -> Result<Tlv> {
        let imei = self.imei.as_bytes();
        if imei.len() != 4 && imei.len() != 8 {
            return Err(EuiccError::MalformedTlv("imei must be 4 or 8 bytes"));
        }
        let device_info = Tlv::constructed(
            Class::ContextSpecific.constructed(1),
            device_info_children(imei)?,
        )?;
        let ctx_children = vec![
            Tlv::primitive(
                Class::ContextSpecific.primitive(0),
                self.matching_id.as_deref().unwrap_or("").as_bytes(),
            )?,
            device_info,
        ];
        let ctx_params = Tlv::constructed(Class::ContextSpecific.constructed(0), ctx_children)?;
        constructed(
            56,
            vec![
                self.signed1.clone(),
                self.signature1.clone(),
                self.used_issuer.clone(),
                self.certificate.clone(),
                ctx_params,
            ],
        )
    }
}

impl CardRequest for AuthenticateServerRequest {
    type Response = AuthenticateServerResponse;

    fn decode_response(&self, tlv: &Tlv) -> Result<Self::Response> {
        AuthenticateServerResponse::from_tlv(tlv)
    }
}

/// ES10b.AuthenticateServer response wrapper.
///
/// # Errors
///
/// Decoding returns [`EuiccError::UnexpectedTag`] when the tag is not `[56]`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AuthenticateServerResponse {
    /// Raw AuthenticateServerResponse TLV.
    pub response: Tlv,
}

impl DecodeTlv for AuthenticateServerResponse {
    fn from_tlv(tlv: &Tlv) -> Result<Self> {
        ensure_tag(tlv, 56, "authenticateServerResponse")?;
        Ok(Self {
            response: tlv.clone(),
        })
    }
}

impl AuthenticateServerResponse {
    /// Decodes the response from a TLV.
    ///
    /// # Errors
    ///
    /// Returns [`EuiccError::UnexpectedTag`] when the tag is not `[56]`.
    pub fn from_tlv(tlv: &Tlv) -> Result<Self> {
        <Self as DecodeTlv>::from_tlv(tlv)
    }
}

impl CardResponse for AuthenticateServerResponse {
    fn validate(&self) -> Result<()> {
        if self
            .response
            .first(&Class::ContextSpecific.constructed(0))
            .is_some()
        {
            return Ok(());
        }
        let Some(choice) = self.response.first(&Class::ContextSpecific.constructed(1)) else {
            return Err(EuiccError::MissingField("authenticateResponseOk"));
        };
        let transaction_id = HexBytes::from_bytes(required_value(
            choice,
            Class::ContextSpecific.primitive(0),
            "transactionId",
        )?);
        let code = AuthenticateErrorCode::from_i64(required_int(
            choice,
            Class::ContextSpecific.primitive(1),
            "authenticateErrorCode",
            1,
        )?);
        Err(AuthenticateResponseError::new(transaction_id, code).into())
    }
}

/// ES10b.CancelSession reason.
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum CancelSessionReason {
    /// End user rejected the operation.
    EndUserRejection,
    /// Download is postponed.
    Postponed,
    /// Session timed out.
    Timeout,
    /// Profile policy rule is not allowed.
    PprNotAllowed,
    /// Metadata mismatch.
    MetadataMismatch,
    /// LoadBoundProfilePackage execution error.
    LoadBppExecutionError,
    /// Undefined reason.
    Undefined,
}

impl CancelSessionReason {
    /// Returns the numeric SGP.22 reason code.
    #[must_use]
    pub const fn code(self) -> i64 {
        match self {
            Self::EndUserRejection => 0,
            Self::Postponed => 1,
            Self::Timeout => 2,
            Self::PprNotAllowed => 3,
            Self::MetadataMismatch => 4,
            Self::LoadBppExecutionError => 5,
            Self::Undefined => 127,
        }
    }
}

/// ES10b.CancelSession request.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CancelSessionRequest {
    /// Transaction id to cancel.
    pub transaction_id: HexBytes,
    /// Cancellation reason.
    pub reason: CancelSessionReason,
}

impl EncodeTlv for CancelSessionRequest {
    fn to_tlv(&self) -> Result<Tlv> {
        constructed(
            65,
            vec![
                Tlv::primitive(
                    Class::ContextSpecific.primitive(0),
                    self.transaction_id.as_bytes(),
                )?,
                Tlv::primitive(
                    Class::ContextSpecific.primitive(1),
                    [self.reason.code() as u8],
                )?,
            ],
        )
    }
}

impl CardRequest for CancelSessionRequest {
    type Response = CancelSessionResponse;

    fn decode_response(&self, tlv: &Tlv) -> Result<Self::Response> {
        CancelSessionResponse::from_tlv(tlv)
    }
}

/// ES10b.CancelSession response wrapper.
///
/// # Errors
///
/// Decoding returns [`EuiccError::UnexpectedTag`] when the tag is not `[65]`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CancelSessionResponse {
    /// Raw CancelSessionResponse TLV.
    pub response: Tlv,
}

impl DecodeTlv for CancelSessionResponse {
    fn from_tlv(tlv: &Tlv) -> Result<Self> {
        ensure_tag(tlv, 65, "cancelSessionResponse")?;
        Ok(Self {
            response: tlv.clone(),
        })
    }
}

impl CancelSessionResponse {
    /// Decodes the response from a TLV.
    ///
    /// # Errors
    ///
    /// Returns [`EuiccError::UnexpectedTag`] when the tag is not `[65]`.
    pub fn from_tlv(tlv: &Tlv) -> Result<Self> {
        <Self as DecodeTlv>::from_tlv(tlv)
    }
}

impl CardResponse for CancelSessionResponse {
    fn validate(&self) -> Result<()> {
        let Some(choice) = self
            .response
            .children()
            .and_then(|children| children.first())
        else {
            return Ok(());
        };
        if choice.tag() == &Class::ContextSpecific.constructed(0) {
            return Ok(());
        }
        if choice.tag() == &Class::ContextSpecific.primitive(1) {
            return match decode_i64(choice.value().unwrap_or_default(), 1)? {
                5 | 127 => Err(EuiccError::Undefined),
                _ => Err(EuiccError::Undefined),
            };
        }
        Err(EuiccError::UnexpectedTag {
            expected: "cancelSessionResponse",
            actual: choice.tag().hex(),
        })
    }
}

macro_rules! inherent_to_tlv {
    ($($ty:ty),+ $(,)?) => {
        $(
            impl $ty {
                /// Encodes this request as an ES10 BER-TLV object.
                ///
                /// # Errors
                ///
                /// Returns protocol validation or TLV construction errors from
                /// the request-specific encoder.

                pub fn to_tlv(&self) -> Result<Tlv> {
                    <Self as EncodeTlv>::to_tlv(self)
                }
            }
        )+
    };
}
inherent_to_tlv!(
    PrepareDownloadRequest,
    LoadBoundProfilePackageRequest,
    GetEuiccChallengeRequest,
    GetEuiccInfoRequest,
    ListNotificationRequest,
    RetrieveNotificationsListRequest,
    NotificationSentRequest,
    AuthenticateServerRequest,
    CancelSessionRequest,
);

macro_rules! inherent_validate {
    ($($ty:ty),+ $(,)?) => {
        $(
            impl $ty {
                /// Validates the decoded ES10 response.
                ///
                /// # Errors
                ///
                /// Returns a protocol-specific [`EuiccError`] for card-level
                /// failure result codes.

                pub fn validate(&self) -> Result<()> {
                    <Self as CardResponse>::validate(self)
                }
            }
        )+
    };
}
inherent_validate!(
    PrepareDownloadResponse,
    LoadBoundProfilePackageResponse,
    GetEuiccChallengeResponse,
    GetEuiccInfoResponse,
    ListNotificationResponse,
    RetrieveNotificationsListResponse,
    NotificationSentResponse,
    AuthenticateServerResponse,
    CancelSessionResponse,
);

fn constructed(value: u64, children: Vec<Tlv>) -> Result<Tlv> {
    Tlv::constructed(Class::ContextSpecific.constructed(value), children)
}

fn octet_string_tag() -> Tag {
    Class::Universal.primitive(4)
}

fn ensure_tag(tlv: &Tlv, value: u64, expected: &'static str) -> Result<()> {
    if !tlv
        .tag()
        .is(Class::ContextSpecific, Form::Constructed, value)
    {
        return Err(EuiccError::UnexpectedTag {
            expected,
            actual: tlv.tag().hex(),
        });
    }
    Ok(())
}

fn required_value<'a>(parent: &'a Tlv, tag: Tag, name: &'static str) -> Result<&'a [u8]> {
    parent
        .first(&tag)
        .and_then(Tlv::value)
        .ok_or(EuiccError::MissingField(name))
}

fn required_fixed_value<'a>(
    parent: &'a Tlv,
    tag: Tag,
    name: &'static str,
    len: usize,
) -> Result<&'a [u8]> {
    let value = required_value(parent, tag, name)?;
    if value.len() != len {
        return Err(EuiccError::MalformedTlv(name));
    }
    Ok(value)
}

fn required_int(parent: &Tlv, tag: Tag, name: &'static str, max_bytes: usize) -> Result<i64> {
    decode_i64(required_value(parent, tag, name)?, max_bytes)
}

fn device_info_children(imei: &[u8]) -> Result<Vec<Tlv>> {
    let mut children = Vec::with_capacity(3);
    children.push(Tlv::primitive(
        Class::ContextSpecific.primitive(0),
        &imei[..4],
    )?);
    children.push(Tlv::constructed(
        Class::ContextSpecific.constructed(1),
        Vec::new(),
    )?);
    if imei.len() == 8 {
        children.push(Tlv::primitive(Class::ContextSpecific.primitive(2), imei)?);
    }
    Ok(children)
}

fn event_filter_bytes(events: &[NotificationEvent]) -> Vec<u8> {
    let mut bits = [false; 4];
    for event in events {
        bits[event.bit_index()] = true;
    }
    encode_bit_string(&bits)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn empty_sequence() -> Tlv {
        Tlv::constructed(Class::Universal.constructed(16), Vec::new())
            .expect("empty sequence TLV builds")
    }

    #[test]
    fn list_notification_response_decodes_context_specific_error() {
        // Arrange
        let tlv =
            Tlv::from_bytes(&[0xBF, 0x28, 0x03, 0x81, 0x01, 0x7F]).expect("response TLV parses");

        // Act
        let result = ListNotificationResponse::from_tlv(&tlv);

        // Assert
        assert!(matches!(result, Err(EuiccError::Undefined)));
    }

    #[test]
    fn retrieve_notifications_response_decodes_context_specific_list() {
        // Arrange
        let tlv = Tlv::from_bytes(&[0xBF, 0x2B, 0x02, 0xA0, 0x00]).expect("response TLV parses");

        // Act
        let response = RetrieveNotificationsListResponse::from_tlv(&tlv).expect("response decodes");

        // Assert
        assert!(response.notifications.is_empty());
    }

    #[test]
    fn notification_sent_response_decodes_context_specific_result() {
        // Arrange
        let tlv =
            Tlv::from_bytes(&[0xBF, 0x30, 0x03, 0x80, 0x01, 0x00]).expect("response TLV parses");

        // Act
        let response = NotificationSentResponse::from_tlv(&tlv).expect("response decodes");

        // Assert
        assert_eq!(response.status, DeleteNotificationStatus::Ok);
    }

    #[test]
    fn authenticate_server_request_matches_context_specific_device_info() {
        // Arrange
        let request = AuthenticateServerRequest {
            transaction_id: HexBytes::from_bytes([0x01]),
            signed1: empty_sequence(),
            signature1: Tlv::primitive(Class::Application.primitive(55), [])
                .expect("signature TLV builds"),
            used_issuer: Tlv::primitive(Class::Universal.primitive(4), [])
                .expect("issuer TLV builds"),
            certificate: empty_sequence(),
            imei: Imei::from_bytes([0x21, 0x43, 0x65, 0x87]),
            matching_id: None,
        };

        // Act
        let bytes = request
            .to_tlv()
            .and_then(|tlv| tlv.to_bytes())
            .expect("request encodes");

        // Assert
        assert_eq!(
            bytes,
            vec![
                0xBF, 0x38, 0x17, 0x30, 0x00, 0x5F, 0x37, 0x00, 0x04, 0x00, 0x30, 0x00, 0xA0, 0x0C,
                0x80, 0x00, 0xA1, 0x08, 0x80, 0x04, 0x21, 0x43, 0x65, 0x87, 0xA1, 0x00,
            ]
        );
    }

    #[test]
    fn authenticate_server_response_validates_context_specific_success_and_error() {
        // Arrange
        let success = Tlv::from_bytes(&[0xBF, 0x38, 0x02, 0xA0, 0x00]).expect("success TLV parses");
        let error = Tlv::from_bytes(&[
            0xBF, 0x38, 0x08, 0xA1, 0x06, 0x80, 0x01, 0x01, 0x81, 0x01, 0x06,
        ])
        .expect("error TLV parses");

        // Act
        let success = AuthenticateServerResponse::from_tlv(&success).and_then(|r| r.validate());
        let error = AuthenticateServerResponse::from_tlv(&error).and_then(|r| r.validate());

        // Assert
        assert!(success.is_ok());
        assert!(matches!(error, Err(EuiccError::Authenticate(_))));
    }

    #[test]
    fn cancel_session_request_matches_context_specific_encoding() {
        // Arrange
        let request = CancelSessionRequest {
            transaction_id: HexBytes::from_bytes([0x01]),
            reason: CancelSessionReason::Postponed,
        };

        // Act
        let bytes = request
            .to_tlv()
            .and_then(|tlv| tlv.to_bytes())
            .expect("request encodes");

        // Assert
        assert_eq!(
            bytes,
            vec![0xBF, 0x41, 0x06, 0x80, 0x01, 0x01, 0x81, 0x01, 0x01]
        );
    }

    #[test]
    fn cancel_session_response_allows_empty_card_result() {
        // Arrange
        let tlv = Tlv::constructed(Class::ContextSpecific.constructed(65), Vec::new())
            .expect("response TLV builds");

        // Act
        let result = CancelSessionResponse::from_tlv(&tlv).and_then(|response| response.validate());

        // Assert
        assert!(result.is_ok());
    }

    #[test]
    fn load_bound_profile_package_error_branch_uses_context_specific_result_fields() {
        // Arrange
        let notification = Tlv::constructed(
            Class::ContextSpecific.constructed(47),
            vec![
                Tlv::primitive(Class::ContextSpecific.primitive(0), [0x01])
                    .expect("sequence TLV builds"),
                Tlv::primitive(
                    Class::ContextSpecific.primitive(1),
                    NotificationEvent::Install.to_bytes(),
                )
                .expect("event TLV builds"),
                Tlv::primitive(Class::Universal.primitive(12), b"smdp.example")
                    .expect("address TLV builds"),
            ],
        )
        .expect("notification TLV builds");
        let final_result = Tlv::constructed(
            Class::ContextSpecific.constructed(2),
            vec![
                Tlv::constructed(
                    Class::ContextSpecific.constructed(1),
                    vec![
                        Tlv::primitive(Class::ContextSpecific.primitive(0), [0x01])
                            .expect("command TLV builds"),
                        Tlv::primitive(Class::ContextSpecific.primitive(1), [0x03])
                            .expect("reason TLV builds"),
                    ],
                )
                .expect("error branch TLV builds"),
            ],
        )
        .expect("final result TLV builds");
        let result = Tlv::constructed(
            Class::ContextSpecific.constructed(39),
            vec![
                Tlv::primitive(Class::ContextSpecific.primitive(0), [0xAA])
                    .expect("transaction TLV builds"),
                final_result,
                notification,
            ],
        )
        .expect("result data TLV builds");
        let tlv = Tlv::constructed(Class::ContextSpecific.constructed(55), vec![result])
            .expect("response TLV builds");

        // Act
        let response = LoadBoundProfilePackageResponse::from_tlv(&tlv).expect("response decodes");

        // Assert
        assert!(matches!(
            response.validate(),
            Err(EuiccError::LoadBoundProfilePackage(_))
        ));
    }
}
